// <auto-generated />
using System;
using EtlTool.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace EtlTool.Data.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260425150152_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "10.0.7");

            modelBuilder.Entity("EtlTool.Core.Models.ColumnMapping", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<Guid>("EtlTaskId")
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsKey")
                        .HasColumnType("INTEGER");

                    b.Property<int>("OrderIndex")
                        .HasColumnType("INTEGER");

                    b.Property<string>("SourceColumn")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<string>("TargetColumn")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<string>("TransformExpression")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("EtlTaskId");

                    b.ToTable("ColumnMappings", (string)null);
                });

            modelBuilder.Entity("EtlTool.Core.Models.ConnectionDefinition", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("EncryptedConnectionString")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<int>("ProviderType")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("Name")
                        .IsUnique();

                    b.ToTable("Connections", (string)null);
                });

            modelBuilder.Entity("EtlTool.Core.Models.EtlTask", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<int>("BatchSize")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("CronExpression")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<string>("DeleteWhereRawSql")
                        .HasColumnType("TEXT");

                    b.Property<bool>("DeleteWhereSameAsFilter")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("Enabled")
                        .HasColumnType("INTEGER");

                    b.Property<string>("FilterFormJson")
                        .HasColumnType("TEXT");

                    b.Property<int>("FilterMode")
                        .HasColumnType("INTEGER");

                    b.Property<string>("FilterRawSql")
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<Guid>("SourceConnectionId")
                        .HasColumnType("TEXT");

                    b.Property<string>("SourceSchema")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("SourceTable")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<Guid>("TargetConnectionId")
                        .HasColumnType("TEXT");

                    b.Property<string>("TargetSchema")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("TargetTable")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("TEXT");

                    b.Property<int>("WriteMode")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("Name")
                        .IsUnique();

                    b.ToTable("EtlTasks", (string)null);
                });

            modelBuilder.Entity("EtlTool.Core.Models.RunHistory", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<string>("ErrorMessage")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("EtlTaskId")
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("FinishedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("GeneratedReadSql")
                        .HasColumnType("TEXT");

                    b.Property<string>("GeneratedWriteSql")
                        .HasColumnType("TEXT");

                    b.Property<long>("RowsRead")
                        .HasColumnType("INTEGER");

                    b.Property<long>("RowsWritten")
                        .HasColumnType("INTEGER");

                    b.Property<string>("SamplePayloadJson")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("StartedAt")
                        .HasColumnType("TEXT");

                    b.Property<int>("Status")
                        .HasColumnType("INTEGER");

                    b.Property<int>("TriggerType")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("EtlTaskId", "StartedAt");

                    b.ToTable("RunHistories", (string)null);
                });

            modelBuilder.Entity("EtlTool.Core.Models.ColumnMapping", b =>
                {
                    b.HasOne("EtlTool.Core.Models.EtlTask", null)
                        .WithMany("Mappings")
                        .HasForeignKey("EtlTaskId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("EtlTool.Core.Models.EtlTask", b =>
                {
                    b.Navigation("Mappings");
                });
#pragma warning restore 612, 618
        }
    }
}
