// <auto-generated />
using System;
using EtlTool.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace EtlTool.Data.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260427052838_AddTaskDependencies")]
    partial class AddTaskDependencies
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "10.0.7");

            modelBuilder.Entity("EtlTool.Core.Models.ApprovalRequest", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<int>("Action")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime?>("DecidedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("DecidedBy")
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<string>("DecisionReason")
                        .HasMaxLength(500)
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("ExpiresAt")
                        .HasColumnType("TEXT");

                    b.Property<int>("Status")
                        .HasColumnType("INTEGER");

                    b.Property<string>("SubmissionReason")
                        .HasMaxLength(500)
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("SubmittedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("SubmittedBy")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<Guid>("TargetId")
                        .HasColumnType("TEXT");

                    b.Property<string>("TargetName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<string>("TargetType")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("Status");

                    b.HasIndex("TargetType", "TargetId", "Status");

                    b.ToTable("ApprovalRequests", (string)null);
                });

            modelBuilder.Entity("EtlTool.Core.Models.AuditEvent", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<int>("Action")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Actor")
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("At")
                        .HasColumnType("TEXT");

                    b.Property<int>("Category")
                        .HasColumnType("INTEGER");

                    b.Property<string>("DetailsJson")
                        .HasColumnType("TEXT");

                    b.Property<string>("Hash")
                        .HasMaxLength(64)
                        .HasColumnType("TEXT");

                    b.Property<string>("Message")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("TEXT");

                    b.Property<string>("PreviousHash")
                        .HasMaxLength(64)
                        .HasColumnType("TEXT");

                    b.Property<int>("Severity")
                        .HasColumnType("INTEGER");

                    b.Property<Guid?>("TargetId")
                        .HasColumnType("TEXT");

                    b.Property<string>("TargetName")
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<string>("TargetType")
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("At");

                    b.HasIndex("Category", "At");

                    b.HasIndex("Severity", "At");

                    b.ToTable("AuditEvents", (string)null);
                });

            modelBuilder.Entity("EtlTool.Core.Models.ColumnMapping", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<Guid>("EtlTaskId")
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsKey")
                        .HasColumnType("INTEGER");

                    b.Property<int>("OrderIndex")
                        .HasColumnType("INTEGER");

                    b.Property<string>("SourceColumn")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<string>("TargetColumn")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<string>("TransformExpression")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("EtlTaskId");

                    b.ToTable("ColumnMappings", (string)null);
                });

            modelBuilder.Entity("EtlTool.Core.Models.ConnectionDefinition", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("EncryptedConnectionString")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("LastCheckError")
                        .HasMaxLength(1000)
                        .HasColumnType("TEXT");

                    b.Property<bool?>("LastCheckOk")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime?>("LastCheckedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<int>("ProviderType")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("Name")
                        .IsUnique();

                    b.ToTable("Connections", (string)null);
                });

            modelBuilder.Entity("EtlTool.Core.Models.EntityChangeHistory", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<int>("Action")
                        .HasColumnType("INTEGER");

                    b.Property<string>("AfterJson")
                        .HasColumnType("TEXT");

                    b.Property<string>("BeforeJson")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("ChangedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("ChangedBy")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<Guid>("EntityId")
                        .HasColumnType("TEXT");

                    b.Property<string>("EntityName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<string>("EntityType")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.Property<string>("Summary")
                        .HasMaxLength(2000)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("ChangedAt");

                    b.HasIndex("EntityType", "EntityId", "ChangedAt");

                    b.ToTable("EntityChangeHistories", (string)null);
                });

            modelBuilder.Entity("EtlTool.Core.Models.EtlTask", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<int?>("AutoDisableAfterFailures")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime?>("AutoDisabledAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("AutoDisabledReason")
                        .HasColumnType("TEXT");

                    b.Property<int>("BatchSize")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("CronExpression")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<string>("DeleteWhereRawSql")
                        .HasColumnType("TEXT");

                    b.Property<bool>("DeleteWhereSameAsFilter")
                        .HasColumnType("INTEGER");

                    b.Property<string>("DependsOnTaskIds")
                        .HasMaxLength(500)
                        .HasColumnType("TEXT");

                    b.Property<bool>("Enabled")
                        .HasColumnType("INTEGER");

                    b.Property<string>("FilterFormJson")
                        .HasColumnType("TEXT");

                    b.Property<int>("FilterMode")
                        .HasColumnType("INTEGER");

                    b.Property<string>("FilterRawSql")
                        .HasColumnType("TEXT");

                    b.Property<bool>("MaskSamplePayload")
                        .HasColumnType("INTEGER");

                    b.Property<long?>("MaxExpectedRows")
                        .HasColumnType("INTEGER");

                    b.Property<int>("MaxRetries")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("MaxRunMinutes")
                        .HasColumnType("INTEGER");

                    b.Property<long?>("MinExpectedRows")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<string>("Notes")
                        .HasMaxLength(2000)
                        .HasColumnType("TEXT");

                    b.Property<string>("PostFailureSp")
                        .HasColumnType("TEXT");

                    b.Property<string>("PostSuccessSp")
                        .HasColumnType("TEXT");

                    b.Property<double>("RetryBackoffMultiplier")
                        .HasColumnType("REAL");

                    b.Property<int>("RetryDelaySeconds")
                        .HasColumnType("INTEGER");

                    b.Property<int>("RowCountPolicy")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("RunHistoryRetentionRuns")
                        .HasColumnType("INTEGER");

                    b.Property<int>("SchemaDriftPolicy")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime?>("SchemaSnapshotAt")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("SourceConnectionId")
                        .HasColumnType("TEXT");

                    b.Property<string>("SourceSchema")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("SourceSchemaSnapshotJson")
                        .HasColumnType("TEXT");

                    b.Property<string>("SourceTable")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<Guid>("TargetConnectionId")
                        .HasColumnType("TEXT");

                    b.Property<string>("TargetSchema")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("TargetSchemaSnapshotJson")
                        .HasColumnType("TEXT");

                    b.Property<string>("TargetTable")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("TEXT");

                    b.Property<int>("WriteMode")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("Name")
                        .IsUnique();

                    b.ToTable("EtlTasks", (string)null);
                });

            modelBuilder.Entity("EtlTool.Core.Models.MaintenanceWindowEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("Days")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<bool>("Enabled")
                        .HasColumnType("INTEGER");

                    b.Property<string>("From")
                        .IsRequired()
                        .HasMaxLength(5)
                        .HasColumnType("TEXT");

                    b.Property<string>("Reason")
                        .HasMaxLength(500)
                        .HasColumnType("TEXT");

                    b.Property<string>("To")
                        .IsRequired()
                        .HasMaxLength(5)
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("MaintenanceWindows", (string)null);
                });

            modelBuilder.Entity("EtlTool.Core.Models.PasswordHistory", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<Guid>("UserId")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("UserId", "CreatedAt");

                    b.ToTable("PasswordHistories", (string)null);
                });

            modelBuilder.Entity("EtlTool.Core.Models.RunHistory", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<string>("ErrorMessage")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("EtlTaskId")
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("FinishedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("GeneratedReadSql")
                        .HasColumnType("TEXT");

                    b.Property<string>("GeneratedWriteSql")
                        .HasColumnType("TEXT");

                    b.Property<long>("RowsRead")
                        .HasColumnType("INTEGER");

                    b.Property<long>("RowsWritten")
                        .HasColumnType("INTEGER");

                    b.Property<string>("SamplePayloadJson")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("StartedAt")
                        .HasColumnType("TEXT");

                    b.Property<int>("Status")
                        .HasColumnType("INTEGER");

                    b.Property<int>("TriggerType")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("EtlTaskId", "StartedAt");

                    b.ToTable("RunHistories", (string)null);
                });

            modelBuilder.Entity("EtlTool.Core.Models.User", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsActive")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime?>("LastLoginAt")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("LastPasswordChangedAt")
                        .HasColumnType("TEXT");

                    b.Property<bool>("MustChangePassword")
                        .HasColumnType("INTEGER");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<int>("Role")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("Username")
                        .IsUnique();

                    b.ToTable("Users", (string)null);
                });

            modelBuilder.Entity("EtlTool.Core.Models.ColumnMapping", b =>
                {
                    b.HasOne("EtlTool.Core.Models.EtlTask", null)
                        .WithMany("Mappings")
                        .HasForeignKey("EtlTaskId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("EtlTool.Core.Models.EtlTask", b =>
                {
                    b.Navigation("Mappings");
                });
#pragma warning restore 612, 618
        }
    }
}
