-- MSSQL 種子資料：在 master 上建一個 EtlTest DB，內含 EMPLOYEES_SRC + EMPLOYEES_TGT
-- 透過 sa 跑

IF DB_ID('EtlTest') IS NULL CREATE DATABASE EtlTest;
GO
USE EtlTest;
GO

IF OBJECT_ID('dbo.EMPLOYEES_SRC') IS NOT NULL DROP TABLE dbo.EMPLOYEES_SRC;
IF OBJECT_ID('dbo.EMPLOYEES_TGT') IS NOT NULL DROP TABLE dbo.EMPLOYEES_TGT;
GO

CREATE TABLE dbo.EMPLOYEES_SRC (
  EMPLOYEE_ID INT NOT NULL PRIMARY KEY,
  FIRST_NAME  NVARCHAR(50) NOT NULL,
  LAST_NAME   NVARCHAR(50) NOT NULL,
  DEPARTMENT_ID INT NULL,
  SALARY      DECIMAL(10,2) NULL,
  HIRE_DATE   DATETIME NULL
);

CREATE TABLE dbo.EMPLOYEES_TGT (
  EMPLOYEE_ID INT NOT NULL PRIMARY KEY,
  FIRST_NAME  NVARCHAR(50) NOT NULL,
  LAST_NAME   NVARCHAR(50) NOT NULL,
  DEPARTMENT_ID INT NULL,
  SALARY      DECIMAL(10,2) NULL,
  HIRE_DATE   DATETIME NULL
);
GO

INSERT INTO dbo.EMPLOYEES_SRC VALUES
  (101, N'frank',  N'Foster',  40, 80000, '2024-06-01'),
  (102, N'grace',  N'Garcia',  40, 82000, '2024-06-15'),
  (103, N'henry',  N'Huang',   50, 90000, '2024-07-01'),
  (104, N'irene',  N'Ito',     50, 95000, '2024-07-20'),
  (105, N'jack',   N'Jones',   60, 75000, '2024-08-10');
GO

SELECT 'MSSQL seed OK' AS msg, COUNT(*) AS n FROM dbo.EMPLOYEES_SRC;
GO
