-- Oracle 種子資料：HR schema 下放兩個表（EMPLOYEES_SRC 為來源、EMPLOYEES_TGT 為目標）
-- 透過 system 帳號跑

ALTER SESSION SET CURRENT_SCHEMA = HR;

BEGIN EXECUTE IMMEDIATE 'DROP TABLE HR.EMPLOYEES_SRC PURGE'; EXCEPTION WHEN OTHERS THEN NULL; END;
/
BEGIN EXECUTE IMMEDIATE 'DROP TABLE HR.EMPLOYEES_TGT PURGE'; EXCEPTION WHEN OTHERS THEN NULL; END;
/

CREATE TABLE HR.EMPLOYEES_SRC (
  EMPLOYEE_ID  NUMBER(10) PRIMARY KEY,
  FIRST_NAME   VARCHAR2(50) NOT NULL,
  LAST_NAME    VARCHAR2(50) NOT NULL,
  DEPARTMENT_ID NUMBER(5),
  SALARY       NUMBER(10,2),
  HIRE_DATE    DATE
);

CREATE TABLE HR.EMPLOYEES_TGT (
  EMPLOYEE_ID  NUMBER(10) PRIMARY KEY,
  FIRST_NAME   VARCHAR2(50) NOT NULL,
  LAST_NAME    VARCHAR2(50) NOT NULL,
  DEPARTMENT_ID NUMBER(5),
  SALARY       NUMBER(10,2),
  HIRE_DATE    DATE
);

INSERT INTO HR.EMPLOYEES_SRC VALUES (1, 'alice', 'Anderson', 10, 50000, DATE '2024-01-15');
INSERT INTO HR.EMPLOYEES_SRC VALUES (2, 'bob',   'Brown',    10, 55000, DATE '2024-02-20');
INSERT INTO HR.EMPLOYEES_SRC VALUES (3, 'carol', 'Chen',     20, 60000, DATE '2024-03-10');
INSERT INTO HR.EMPLOYEES_SRC VALUES (4, 'dave',  'Davis',    20, 62000, DATE '2024-04-05');
INSERT INTO HR.EMPLOYEES_SRC VALUES (5, 'eve',   'Evans',    30, 70000, DATE '2024-05-12');
COMMIT;

SELECT 'Oracle seed OK, rows:' AS msg, COUNT(*) AS n FROM HR.EMPLOYEES_SRC;
